name: Crear Tag Producción

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Número de versión para producción (ej: 1.0.1)"
        required: true
      comentario:
        description: "Comentario sobre la versión"
        required: false

jobs:
  crear-tag:
    name: Crear y subir Tag Producción
    runs-on: ubuntu-latest

    steps:
      - name: 🔁 Clonar el repositorio con todos los tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para trabajar con tags

      - name: 🏷️ Comprobar si el tag ya existe y crearlo si no
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          TAG_NAME="v${{ github.event.inputs.version }}"
          COMMENT="${{ github.event.inputs.comentario }}"

          if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
            echo "⚠️ El tag $TAG_NAME ya existe. No se creará nuevamente."
            exit 0
          fi

          git tag -a "$TAG_NAME" -m "$COMMENT"
          git push origin "$TAG_NAME"
